fix: handle case when dataset specification is missing
Error: 	Cannot read properties of undefined (reading 'fields')
Trigger: GET /organisations/local-authority:BUC/listed-building/overview

The fetched specification collecton doesn't containa a spec for
the dataset ('listed-building' in our example)