fix: safely handle missing resource id
Error: Cannot read properties of undefined (reading 'resource')
Trigger: GET /organisations/local-authority:MEN/brownfield-land

We get an empty string id when fetching resource status and that
causes things to fail further down. Upadted the code to skip attempted
fetch of entity count and setting it to zero.