fix: default data to zero/[] when resource missing, limit max pages num.
Error: Cannot read properties of undefined (reading '0')
Trigger: GET /organisations/local-authority:SAL/tree/invalid%20date/entry-date/5000

This is further fix, for the above: Added safe default values, so
a page can't be displayed (but with missing data, so it's obviously
looks broken).

To take care of the "brokn look" we disallow going to pages that
are missing data (e.g. no data to display returned from datasette)